import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ReduxProvider } from "@/common/ReduxProvider";
import { Toaster } from "react-hot-toast";
import Header from "./components/Header/Header";
import FooterBar from "./components/FooterBar/FooterBar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <Toaster/>
          <div className="sticky top-0 w-full z-20">
            <Header/>
          </div>
        {children}
       { <div className="z-30 fixed bottom-0 w-full">
        <FooterBar/>
        </div>}
        </ReduxProvider>
      </body>
    </html>
  );
}
